# -*- coding: utf-8 -*-
"""Sampling_Quantization_Coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlS6wUdjs8kwiI-2YeX9Ysp5kck58xXh
"""

#x(t)=cos(2*pi*f*t)  plotting from t(-1,1)
import numpy as np
import matplotlib.pyplot as plt

tmin=-1
tmax=1
num_t=1000
t=np.linspace(tmin,tmax,num_t)
#print(t)
f=2
xt=np.cos(2*np.pi*f*t)
plt.plot(t,xt)
plt.xlabel("t")
plt.ylabel("Amplitude")
plt.title("Plot of cosine function")

#sampling
Fs=30
Ts=1/Fs
pulse_train=np.arange(tmin,tmax, Ts)
#print(pulse_train)
xt_sampled=np.cos(2*np.pi*f*pulse_train)
plt.stem(pulse_train,xt_sampled)
plt.plot(t,xt,'r')

xmin = min(xt_sampled)
xmax = max(xt_sampled)

labels = 11
quantization_step = (xmax - xmin) / (labels - 1)

quantized_signal = np.round((xt_sampled - xmin) / quantization_step) * quantization_step + xmin


plt.figure()
plt.stem(pulse_train,quantized_signal)
#plt.plot(t, xt, 'r')

for label_value in np.arange(xmin, xmax + quantization_step, quantization_step):
    plt.axhline(y=label_value, color='g', linestyle='--')

plt.xlabel("Time")
plt.ylabel("Amplitude")
plt.title("Quantized Signal with Quantization Labels")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

n = np.arange(-10,11)

#unit Sample Sequence
unit_sample = np.zeros_like(n)
unit_sample[n==0] = 1

#Unit Step Sequence
unit_step = np.heaviside(n,0)


#Unit ramp Sequence
unit_ramp = np.maximum(n,1)


#Plotting the signals.
fig, axs = plt.subplots(3,2,figsize=(8,8))
axs[0][0].stem(n, unit_sample)
axs[0][0].set_title('Unit Sample Sequence.')

axs[1][0].stem(n, unit_step)
axs[1][0].set_title('Unit Step Sequence.')

axs[2][0].stem(n,unit_ramp)
axs[2][0].set_title('Unit Ramp Sequence.')


plt.tight_layout()
plt.show()